name: Keep Alive
on:
  schedule:
    - cron: '*/4 * * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Visit app
        run: |
          curl -s -L -H "User-Agent: Mozilla/5.0" "https://ldqdgjrfdhzsmbgj3p22gn.streamlit.app/" > /dev/null
          echo "✅ Done at $(date)"
